name: CI - Run Tests

on:
  push:
    branches: [ feature/docker-ci-cd, dev ]
  pull_request:
    branches: [ feature/docker-ci-cd, dev ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and run tests with Docker Compose
        run: docker compose -f docker-compose-test.yml up --build --exit-code-from littleneighbors_tests

      - name: Upload Test Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports
          retention-days: 1

      - name: Cleanup
        if: always()
        run: docker compose -f docker-compose-test.yml down -v